/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lavacar;
 
import java.io.File;
import java.net.URISyntaxException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author angie
 */
public class CobrarOrden  extends javax.swing.JFrame {
    static DefaultTableModel modelo;
    ConexionBD cc = new ConexionBD();
    Connection cn = cc.conexion();
    public CobrarOrden() {
        initComponents();
        modelo = (DefaultTableModel) jTable1.getModel();
        mostrarDatos("");
    }
     void mostrarDatos(String valor) {
        DefaultTableModel modelo = new DefaultTableModel();
        
        modelo.addColumn("Numero_de_placa"); //0
        modelo.addColumn("tipo_vehiculo"); //1
        modelo.addColumn("id_cliente"); //2
        modelo.addColumn("nombe_cliente");//3
        modelo.addColumn("telefono_cliente"); //4
        modelo.addColumn("correo_cliente"); //5
        modelo.addColumn("tipo_servicio");// 6
        
        
        jTable1.setModel(modelo);

        String datos[] = new String[7];
        String sql = "";
        if(valor.equals("")){
                   // aca muestra todos los valores
                   sql="SELECT * FROM orden_de_trabajo WHERE estado_orden = 'Activa'";
               }else{
                   // aqui solo muestra el buscado con WHERE
                   // recordar si se puede hacer un swtch para poder buscar en toas las columnas
                   sql = "SELECT * FROM orden_de_trabajo WHERE Numero_de_placa = '"+ valor +"'";
               }
        
        try {
            int j = 0;
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                for (int i = 0; i < datos.length; i++) {
                   
                   // if (i == 0 || i == 1 || i == 3 || i == 6){    
                    datos[i] = rs.getString(i+1);
                     //j++;
                    //} 
                }
                modelo.addRow(datos);
            }
            jTable1.setModel(modelo);
        } catch (SQLException e) {
            System.err.println(e.toString());
        }
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbGenerarFactura = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jbMostrarDatos = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jbGenerarFactura.setText("Generar Factura");
        jbGenerarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGenerarFacturaActionPerformed(evt);
            }
        });

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbMostrarDatos.setText("Mostrar Datos");
        jbMostrarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMostrarDatosActionPerformed(evt);
            }
        });

        jButton3.setText("Atras");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbMostrarDatos))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 283, Short.MAX_VALUE)
                        .addComponent(jbBuscar)
                        .addGap(26, 26, 26)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jbGenerarFactura)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton3)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbBuscar)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jbMostrarDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jbGenerarFactura)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbGenerarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGenerarFacturaActionPerformed
        int fila =jTable1.getSelectedRow();
        
        String numero_placa = null;
        String tipo = null;
        String identificacion = null;
        String nombre=null;
        String telefono=null;
        String servicio=null;
         for (int i = fila; i >=0; i--) {
            
           numero_placa=jTable1.getValueAt(fila, 0).toString();
           tipo=jTable1.getValueAt(fila, 1).toString();
           identificacion=jTable1.getValueAt(fila, 2).toString();
           nombre=jTable1.getValueAt(fila, 3).toString();
           telefono=jTable1.getValueAt(fila, 4).toString();
           servicio=jTable1.getValueAt(fila, 6).toString();
           
        } 
        String path="C:\\Users\\hanse\\Desktop\\progra2\\Lavacar-_1_\\Lavacar (1)\\Lavacar\\src\\lavacar\\Factura.jasper";
        JasperReport reporte;
        try {
          reporte =(JasperReport)JRLoader.loadObject(path);
            Map parametro = new HashMap();
                parametro.put("numero_placa", numero_placa);          
                parametro.put("tipo",tipo);
                parametro.put("identificacion",identificacion);
                parametro.put("nombre",nombre);
                parametro.put("telefono",telefono);
                parametro.put("servicio",servicio);   
           //agrgar los elementos
            JasperPrint jprint= JasperFillManager.fillReport(path, parametro, new JREmptyDataSource());
            
            //parte visualizacion  
            JasperViewer viewer= new JasperViewer(jprint,false);
            viewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            viewer.setVisible(true);
            
        } catch (JRException ex) {
            Logger.getLogger(CobrarOrden.class.getName()).log(Level.SEVERE, null, ex);
        }

    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
 int fila =jTable1.getSelectedRow();
      if(fila>=0){
          try {
            PreparedStatement pst = cn.prepareStatement("DELETE FROM orden_de_trabajo WHERE Numero_de_placa ='"+jTable1.getValueAt(fila, 0).toString()+"'");
            pst.executeUpdate();
            mostrarDatos("");
                    
          } catch (SQLException e) {
              System.err.println(e.toString());
          }
          
      }else {
      JOptionPane.showMessageDialog(null," No seleccionado ninguna orden , porfavor seleciones alguna orden de la tabla ");
      }

    }//GEN-LAST:event_jbGenerarFacturaActionPerformed

    private void jbMostrarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMostrarDatosActionPerformed
        mostrarDatos("");
    }//GEN-LAST:event_jbMostrarDatosActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        mostrarDatos(jTextField1.getText());
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        MenuPrincipal mn= new MenuPrincipal();
        mn.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CobrarOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CobrarOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CobrarOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CobrarOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CobrarOrden().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbGenerarFactura;
    private javax.swing.JButton jbMostrarDatos;
    // End of variables declaration//GEN-END:variables
}
