/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lavacar;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static lavacar.MantenimientoUsuario.modelo;

/**
 *
 * @author angie
 */
public class MantenimientoServicios extends javax.swing.JFrame {
    ConexionBD cc = new ConexionBD();
    Connection cn = cc.conexion();
    DefaultTableModel modelo;
    public MantenimientoServicios() {
        initComponents();
        modelo=(DefaultTableModel) jtServicios.getModel();
        mostrarDatos("");
    }
    void mostrarDatos(String valor) {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Servicios");
        modelo.addColumn("Precio");
        jtServicios.setModel(modelo);

        String datos[] = new String[2];
        String sql = "";
        if (valor.equals("")) {
            sql = "SELECT * FROM servicios";
        } else {
            sql = "SELECT * FROM usuarios WHERE servicios= '" + valor + "'";
        }
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                for (int i = 0; i < datos.length; i++) {
                    datos[i] = rs.getString(i + 1);
                }
                modelo.addRow(datos);
            }
            jtServicios.setModel(modelo);
        } catch (SQLException e) {
            System.err.println(e.toString());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbAgregar = new javax.swing.JButton();
        jdEliminar = new javax.swing.JButton();
        jdModificar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtfAgregar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtServicios = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jtfPrecio = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jdMostrar = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        jdEliminar.setText("Eliminar");
        jdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdEliminarActionPerformed(evt);
            }
        });

        jdModificar.setText("Modificar");
        jdModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdModificarActionPerformed(evt);
            }
        });

        jLabel2.setText("Agregar Servicio");

        jtServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtServicios);

        jLabel3.setText("Precio");

        jtfPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPrecioActionPerformed(evt);
            }
        });

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jdMostrar.setText("Mostrar datos");
        jdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdMostrarActionPerformed(evt);
            }
        });

        jbGuardar.setText("Guardar Modificacion");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jtfAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jdEliminar)
                                        .addGap(47, 47, 47)
                                        .addComponent(jbAgregar)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(jbGuardar))))
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jdModificar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jbBuscar)
                        .addGap(30, 30, 30)
                        .addComponent(jdMostrar)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbBuscar)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdMostrar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jdEliminar)
                    .addComponent(jbAgregar)
                    .addComponent(jbGuardar))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jdModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdModificarActionPerformed
   int filasSeleccionada=jtServicios.getSelectedRow();
   if(filasSeleccionada>=0){
       jtfAgregar.setText(jtServicios.getValueAt(filasSeleccionada, 0).toString());
       jtfPrecio.setText(jtServicios.getValueAt(filasSeleccionada, 1).toString());
   
   }
   else {
  JOptionPane.showMessageDialog(null, "No selecciono ninguna fila", "Error", JOptionPane.ERROR_MESSAGE);

   }
    }//GEN-LAST:event_jdModificarActionPerformed

    private void jdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdEliminarActionPerformed
        int fila =jtServicios.getSelectedRow();
      if(fila>=0){
          try {
            PreparedStatement pst = cn.prepareStatement("DELETE FROM servicios WHERE servicio='"+jtServicios.getValueAt(fila, 0).toString()+"'");
            pst.executeUpdate();
            mostrarDatos("");
                    
          } catch (SQLException e) {
              System.err.println(e.toString());
          }
          
      }else {
      JOptionPane.showMessageDialog(null," No a seleccionado ningun  Servicio , porfavor seleciones un servicio de la tabla ");
      }
    }//GEN-LAST:event_jdEliminarActionPerformed

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
 double precio = Double.parseDouble(jtfPrecio.getText());
ConexionBD cc = new ConexionBD();
                Connection cn = cc.conexion();
                try {
                    // Creamos una varible tipo pepared statement que almacenara un Inert into que debera almacenar datos 
                    PreparedStatement pst = cn.prepareStatement("INSERT INTO servicios(servicio, precio)VALUES(?, ?)");

                    // le enviamos el valor de la caja de texto a la columna 1 con SetString
                    pst.setString(1, jtfAgregar.getText());
                    pst.setDouble(2, precio);
                    
                    // el executeUpdate es para subir los datos a la base de datos 
                    int a = pst.executeUpdate();
                    if (a > 0) {
                        JOptionPane.showMessageDialog(null, "Orden agregada con exito");
                        jtfAgregar.setText("");
                        jtfPrecio.setText("");
                       
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al agregar");
                    }
                } catch (Exception e) {
                    System.err.println(e.toString());
                }
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void jtfPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPrecioActionPerformed

    private void jdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdMostrarActionPerformed
        mostrarDatos("");
    }//GEN-LAST:event_jdMostrarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        mostrarDatos(jTextField1.getText());
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
       double precio = Double.parseDouble(jtfPrecio.getText());
ConexionBD cc = new ConexionBD();
                Connection cn = cc.conexion();
                try {
                    PreparedStatement pst = cn.prepareStatement("UPDATE servicios SET servicio=?, precio=?");

                    pst.setString(1, jtfAgregar.getText());
                    pst.setDouble(2, precio);
                    
                    int a = pst.executeUpdate();
                    if (a > 0) {
                        JOptionPane.showMessageDialog(null, "Orden agregada con exito");
                        jtfAgregar.setText("");
                        jtfPrecio.setText("");
                       
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al agregar");
                    }
                } catch (Exception e) {
                    System.err.println(e.toString());
                }
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     MenuPrincipal mn= new MenuPrincipal();
        mn.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantenimientoServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantenimientoServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantenimientoServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantenimientoServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantenimientoServicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jdEliminar;
    private javax.swing.JButton jdModificar;
    private javax.swing.JButton jdMostrar;
    private javax.swing.JTable jtServicios;
    private javax.swing.JTextField jtfAgregar;
    private javax.swing.JTextField jtfPrecio;
    // End of variables declaration//GEN-END:variables
}
