/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lavacar;

import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static lavacar.CobrarOrden.modelo;

/**
 *
 * @author angie
 */
public class MantenimientoUsuario extends javax.swing.JFrame {

    boolean validarUsuario = false;
    boolean validarContraseña = false;
    boolean validarCorreo = false;
    static DefaultTableModel modelo;
    ConexionBD cc = new ConexionBD();
    Connection cn = cc.conexion();

    public MantenimientoUsuario() {
        initComponents();
        modelo = (DefaultTableModel) jtUsuario.getModel();
        mostrarDatos("");
    }

    void mostrarDatos(String valor) {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Usuario");
        modelo.addColumn("Contraseña");
        modelo.addColumn("Nombre");
        modelo.addColumn("Tipo");
        modelo.addColumn("identiicacion");
        modelo.addColumn("Correo");
        jtUsuario.setModel(modelo);

        String datos[] = new String[6];
        String sql = "";
        if (valor.equals("")) {
            sql = "SELECT * FROM usuarios";
        } else {
            sql = "SELECT * FROM usuarios WHERE usuario= '" + valor + "'";
        }
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                for (int i = 0; i < datos.length; i++) {
                    datos[i] = rs.getString(i + 1);
                }
                modelo.addRow(datos);
            }
            jtUsuario.setModel(modelo);
        } catch (SQLException e) {
            System.err.println(e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtUsuario = new javax.swing.JTable();
        jdModificar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfIdentificacion = new javax.swing.JTextField();
        jtfUsuario = new javax.swing.JTextField();
        jtfNombre = new javax.swing.JTextField();
        jtfCorreo = new javax.swing.JTextField();
        jtfContraseña = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jdAgregar = new javax.swing.JButton();
        jdEliminar = new javax.swing.JButton();
        jdGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtUsuario);

        jdModificar.setText("Modificar");
        jdModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdModificarActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre");

        jLabel5.setText("Clave");

        jLabel6.setText("Tipo");

        jtfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador ", "Usuario" }));

        jdAgregar.setText("Agregar");
        jdAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdAgregarActionPerformed(evt);
            }
        });

        jdEliminar.setText("Eliminar");
        jdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdEliminarActionPerformed(evt);
            }
        });

        jdGuardar.setText("Guardar modficacion");
        jdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdGuardarActionPerformed(evt);
            }
        });

        jLabel1.setText("Identificacion");

        jLabel2.setText("Usuario");

        jLabel3.setText("Correo");

        jLabel8.setText("Contraseña");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jdGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(jdEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(jdAgregar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtfIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jdModificar)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jdModificar)
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jtfIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jdAgregar)
                    .addComponent(jdEliminar)
                    .addComponent(jdGuardar))
                .addContainerGap())
        );

        jTextField1.setText("Usuario");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jButton5.setText("Mostrar Datos");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jbBuscar)
                .addGap(38, 38, 38)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jdAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdAgregarActionPerformed
        validarUsuario();
        validarContraseña();
        validarCorreo();
        if (validarUsuario == true && validarContraseña == true && validarCorreo == true) {
            if (validarUsuario == true && validarContraseña == true) {
                ConexionBD cc = new ConexionBD();
                Connection cn = cc.conexion();
                try {
                    // Creamos una varible tipo pepared statement que almacenara un Inert into que debera almacenar datos 
                    PreparedStatement pst = cn.prepareStatement("INSERT INTO usuarios(usuario, contraseña, nombre_usuario, tipo, identificacion, Correo)VALUES(?, ?, ?, ?, ?, ?)");

                    // le enviamos el valor de la caja de texto a la columna 1 con SetString
                    pst.setString(1, jtfUsuario.getText());
                    pst.setString(2, jtfContraseña.getText());
                    pst.setString(3, jtfNombre.getText());
                    pst.setString(4, (String) jComboBox1.getSelectedItem());
                    pst.setString(5, jtfIdentificacion.getText());
                    pst.setString(6, jtfCorreo.getText());
                    // el executeUpdate es para subir los datos a la base de datos 
                    int a = pst.executeUpdate();
                    if (a > 0) {
                        JOptionPane.showMessageDialog(null, "Orden agregada con exito");
                        jtfContraseña.setText("");
                        jtfNombre.setText("");
                        jtfUsuario.setText("");
                        jtfIdentificacion.setText("");
                        jtfCorreo.setText("");
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al agregar");
                    }
                } catch (Exception e) {
                    System.err.println(e.toString());
                }
            }
        } else if (validarUsuario == false && validarContraseña == false) {
            JOptionPane.showMessageDialog(null, "Datos incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (validarContraseña == false) {
            JOptionPane.showMessageDialog(null, "Ingreso la contraseña incorrecta", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (validarUsuario == false) {
            JOptionPane.showMessageDialog(null, "Ingreso el usuario incorrecto", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (validarCorreo == false) {
            JOptionPane.showMessageDialog(null, "Ingreso el correo incorrecto", "Error", JOptionPane.ERROR_MESSAGE);
        }
        validarCorreo = false;
        validarContraseña = false;
        validarUsuario = false;
    }//GEN-LAST:event_jdAgregarActionPerformed
    public void validarCorreo() {
        String correo = jtfCorreo.getText();
        if (correo.contains("@") == true) {
            validarCorreo = true;
        }

    }

    public void validarUsuario() {
        String usuario = jtfUsuario.getText();
        if (usuario.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Error al ingresar el usuario", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (usuario.length() <= 8) {
                char letra = usuario.charAt(0);
                if (Character.isUpperCase(letra)) {
                    validarUsuario = true;
                }
            }
        }
    }

    public void validarContraseña() {
        String contraseña = jtfContraseña.getText();
        if (contraseña.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Error al ingresar el usuario", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (contraseña.length() <= 8) {
                char caracter = contraseña.charAt(0);
                if (Character.isUpperCase(caracter)) {
                    if (contraseña.contains(".") == true) {
                        validarContraseña = true;
                    }
                }
            }
        }
 
    }

    private void jdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdEliminarActionPerformed
      int fila =jtUsuario.getSelectedRow();
      if(fila>=0){
          try {
            PreparedStatement pst = cn.prepareStatement("DELETE FROM usuarios WHERE usuario='"+jtUsuario.getValueAt(fila, 0).toString()+"'");
            pst.executeUpdate();
            mostrarDatos("");
                    
          } catch (SQLException e) {
              System.err.println(e.toString());
          }
          
      }else {
      JOptionPane.showMessageDialog(null," No seleccionado ningun  servicio , porfavor seleciones un servicio de la tabla ");
      }
        
    }//GEN-LAST:event_jdEliminarActionPerformed

    private void jtfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreActionPerformed

    private void jdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdGuardarActionPerformed
 ConexionBD cc = new ConexionBD();
  Connection cn = cc.conexion();
               try{
            // creamos una variable tipo prepared statement que almacenara un UPDATE que debera sobreescribir donde se hace referencia al WHERE
            // nombre de las columnas
            PreparedStatement pst = cn.prepareStatement("UPDATE usuarios SET contraseña = '"+jtfContraseña.getText()+"'"
                    + ", nombre_usuario = '"+jtfNombre.getText()+"'"
                    + ", tipo = '"+jComboBox1.getSelectedItem()+"'" 
                    + ", identificacion = '"+jtfIdentificacion.getText()+"'"
                    + ", correo = '"+jtfCorreo.getText()+"'"
                    + "WHERE usuario ='"+jtfUsuario.getText()+"'");
             

            int a=pst.executeUpdate();

            if(a>0){

                JOptionPane.showMessageDialog(null,"Orden modificada con éxito");
                

            }
            else{
                JOptionPane.showMessageDialog(null,"Error al modificar");
            }
        }catch(Exception e){
            System.err.println(e.toString());
        } 
    }//GEN-LAST:event_jdGuardarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        mostrarDatos(jTextField1.getText());
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        mostrarDatos("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        char teclaPresionada = evt.getKeyChar();
        if (teclaPresionada == KeyEvent.VK_ENTER) {
            jbBuscar.doClick();
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jdModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdModificarActionPerformed
       int filasSeleccionada = jtUsuario.getSelectedRow();
        if (filasSeleccionada >= 0) {
            jtfContraseña.setText(jtUsuario.getValueAt(filasSeleccionada, 1).toString());
            jtfCorreo.setText(jtUsuario.getValueAt(filasSeleccionada, 5).toString());
            jtfUsuario.setText(jtUsuario.getValueAt(filasSeleccionada, 0).toString());
            jtfIdentificacion.setText(jtUsuario.getValueAt(filasSeleccionada, 4).toString());
            jtfNombre.setText(jtUsuario.getValueAt(filasSeleccionada, 2).toString());
            //modelo.removeRow(filasSeleccionada);
        } else {
            JOptionPane.showMessageDialog(null, "No ingreso selecciono ninguna fila", "Error", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_jdModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantenimientoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantenimientoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantenimientoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantenimientoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantenimientoUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jdAgregar;
    private javax.swing.JButton jdEliminar;
    private javax.swing.JButton jdGuardar;
    private javax.swing.JButton jdModificar;
    private javax.swing.JTable jtUsuario;
    private javax.swing.JTextField jtfContraseña;
    private javax.swing.JTextField jtfCorreo;
    private javax.swing.JTextField jtfIdentificacion;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables
}
