/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lavacar;

import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author hanse
 */
public class ModificarOrden extends javax.swing.JFrame {


    private String placa, tipo, idcliente, tiposervicio;;
    
    public ModificarOrden() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    // usar este metodo para recibir el valor de placa asignado en la lista de ordenes para ponerlo en los txt field de este jframe
        public void setDatos(String placa, String tipo, String idcliente, String tiposervicio) {
        this.placa = placa;
        this.tipo = tipo;
        this.idcliente = idcliente;
        this.tiposervicio = tiposervicio;
        
        // enviamos el registro al txt field
        jtfPlacaVehiculo.setText(placa);
        jcbTipoVehiculo.setSelectedItem(tipo);
        jtfIdCliente.setText(idcliente);
        jcbTipoServicio.setSelectedItem(tiposervicio);
        
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpSuperior = new javax.swing.JPanel();
        jlHora = new javax.swing.JLabel();
        jbMostraMenu = new javax.swing.JButton();
        jbGenerarOT = new javax.swing.JButton();
        jpSuperior1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jtfPlacaVehiculo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jcbTipoVehiculo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jtfIdCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jcbTipoServicio = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        jpSuperior.setBackground(new java.awt.Color(0, 153, 153));

        jlHora.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jlHora.setForeground(new java.awt.Color(255, 255, 255));

        jbMostraMenu.setBackground(new java.awt.Color(0, 153, 153));
        jbMostraMenu.setForeground(new java.awt.Color(0, 153, 153));
        jbMostraMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        jbMostraMenu.setBorder(null);
        jbMostraMenu.setContentAreaFilled(false);
        jbMostraMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbMostraMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMostraMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpSuperiorLayout = new javax.swing.GroupLayout(jpSuperior);
        jpSuperior.setLayout(jpSuperiorLayout);
        jpSuperiorLayout.setHorizontalGroup(
            jpSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbMostraMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(694, 694, 694)
                .addComponent(jlHora, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpSuperiorLayout.setVerticalGroup(
            jpSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSuperiorLayout.createSequentialGroup()
                .addGroup(jpSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpSuperiorLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jlHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpSuperiorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbMostraMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jbGenerarOT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbGenerarOT.setText("Modificar orden de trabajo");
        jbGenerarOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGenerarOTActionPerformed(evt);
            }
        });

        jpSuperior1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Modificar Orden");

        javax.swing.GroupLayout jpSuperior1Layout = new javax.swing.GroupLayout(jpSuperior1);
        jpSuperior1.setLayout(jpSuperior1Layout);
        jpSuperior1Layout.setHorizontalGroup(
            jpSuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSuperior1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(298, Short.MAX_VALUE))
        );
        jpSuperior1Layout.setVerticalGroup(
            jpSuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSuperior1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtfPlacaVehiculo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Tipo de vehiculo:");

        jcbTipoVehiculo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbTipoVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Sedan", "SUV", "4x4", "Motocicleta", "Camión" }));
        jcbTipoVehiculo.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Identificación de cliente:");

        jtfIdCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Tipo de servicio:");

        jcbTipoServicio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbTipoServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Lavado", "Aspirado", "Encerado", "Lavado y apirado", "Lavado aspirado y encerado" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Número de placa de vehiculo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpSuperior1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jbGenerarOT))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfPlacaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbTipoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpSuperior1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPlacaVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbTipoVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfIdCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbTipoServicio, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel7))
                .addGap(61, 61, 61)
                .addComponent(jbGenerarOT)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbGenerarOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGenerarOTActionPerformed

        ConexionBD cc=new ConexionBD();
        // volvemos a crear una variable tipo connection que recibira el valor del metodo conexion y se alamcena en la variable cn
        Connection cn=cc.conexion();

        try{
            // creamos una variable tipo prepared statement que almacenara un UPDATE que debera sobreescribir donde se hace referencia al WHERE
            // nombre de las columnas
            PreparedStatement pst = cn.prepareStatement("UPDATE orden_de_trabajo SET vehiculo = '"+jcbTipoVehiculo.getSelectedItem()+"'"
                    + ", id_cliente = '"+jtfIdCliente.getText()+"'"
                    + ", tipo_servicio = '"+jcbTipoServicio.getSelectedItem()+"'"
                    + "WHERE Numero_de_placa ='"+jtfPlacaVehiculo.getText()+"'");
             

            int a=pst.executeUpdate();

            if(a>0){

                JOptionPane.showMessageDialog(null,"Orden modificada con éxito");
                dispose();
                
            }
            else{
                JOptionPane.showMessageDialog(null,"Error al modificar");
            }
        }catch(Exception e){
            System.err.println(e.toString());
        }        // TODO
    }//GEN-LAST:event_jbGenerarOTActionPerformed

    private void jbMostraMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMostraMenuActionPerformed
        
    }//GEN-LAST:event_jbMostraMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarOrden().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbGenerarOT;
    private javax.swing.JButton jbMostraMenu;
    private javax.swing.JComboBox<String> jcbTipoServicio;
    private javax.swing.JComboBox<String> jcbTipoVehiculo;
    private javax.swing.JLabel jlHora;
    private javax.swing.JPanel jpSuperior;
    private javax.swing.JPanel jpSuperior1;
    private javax.swing.JTextField jtfIdCliente;
    private javax.swing.JTextField jtfPlacaVehiculo;
    // End of variables declaration//GEN-END:variables
}
