/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lavacar;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author hanse
 */
public class Orden extends javax.swing.JPanel {

    /**
     * Creates new form Orden
     */
    public Orden() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfPlacaVehiculo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jcbTipoVehiculo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jtfIdCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jcbTipoServicio = new javax.swing.JComboBox<>();
        jbGenerarOT = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Número de placa de vehiculo:");

        jtfPlacaVehiculo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Tipo de vehiculo:");

        jcbTipoVehiculo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbTipoVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Sedan", "SUV", "4x4", "Motocicleta", "Camión" }));
        jcbTipoVehiculo.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Identificación de cliente:");

        jtfIdCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Tipo de servicio:");

        jcbTipoServicio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbTipoServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Lavado", "Aspirado", "Encerado", "Lavado y apirado", "Lavado aspirado y encerado" }));

        jbGenerarOT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbGenerarOT.setText("Generar orden de trabajo");
        jbGenerarOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGenerarOTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jcbTipoVehiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfIdCliente)
                    .addComponent(jtfPlacaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbTipoServicio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jbGenerarOT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPlacaVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbTipoVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfIdCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbTipoServicio, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel7))
                .addGap(63, 63, 63)
                .addComponent(jbGenerarOT)
                .addGap(92, 92, 92))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbGenerarOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGenerarOTActionPerformed
        
        ConexionBD cc=new ConexionBD();
        // volvemos a crear una variable tipo connection que recibira el valor del metodo conexion y se alamcena en la variable cn
        Connection cn=cc.conexion();

        try{
            // creamos una variable tipo prepared statement que almacenara un INSERT INTO que debera alamecenar datos
            // nombre de las columnas
            PreparedStatement pst = cn.prepareStatement("INSERT INTO orden_de_trabajo(Numero_de_placa, vehiculo, id_cliente, tipo_servicio, estado_orden) VALUES(?, ?, ?, ?, ?)");
            // nombre de la bd(nombre de la tabla) VALUES(tantas ? como columnas)
            // le enviamos el valor de la caje de texto a la columna 1 con un setString
            pst.setString(1, jtfPlacaVehiculo.getText());
            pst.setString(2, (String) jcbTipoVehiculo.getSelectedItem());
            pst.setString(3, jtfIdCliente.getText());
            pst.setString(4, (String) jcbTipoServicio.getSelectedItem());
            pst.setString(5, "Activa");

            // el executeUpdate es para  gurdar  bd
            int a=pst.executeUpdate();
            
            
             String id = "";
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery("SELECT * FROM clientes WHERE id_cliente ='"+jtfIdCliente.getText()+"'");
            
            while(rs.next()){
                id =rs.getString("id_cliente");
            }
            
            if(id.equals("")){
            JOptionPane.showMessageDialog(null,"El cliente no a sido registrado, por favor registrar el nuevo cliente","Error al generar orden",JOptionPane.OK_OPTION);
            MantenimientoCliente mc = new MantenimientoCliente();
            mc.setVisible(true);
            mc.setDatos(jtfIdCliente.getText());
            }
            
            if(a>0){ 
                
                jtfPlacaVehiculo.setText("");
                jcbTipoVehiculo.setSelectedItem("");
                jtfIdCliente.setText("");
                jcbTipoServicio.setSelectedItem("");

            }
            else{
                JOptionPane.showMessageDialog(null,"Error al agregar");
            }
        }catch(Exception e){
            System.err.println(e.toString());
        }

    }//GEN-LAST:event_jbGenerarOTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbGenerarOT;
    private javax.swing.JComboBox<String> jcbTipoServicio;
    private javax.swing.JComboBox<String> jcbTipoVehiculo;
    private javax.swing.JTextField jtfIdCliente;
    private javax.swing.JTextField jtfPlacaVehiculo;
    // End of variables declaration//GEN-END:variables
}
